name: Deploy Frontend to Cloud Run

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/content-optimizer-frontend ./frontend

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2

      - name: Push Docker image
        run: |
          gcloud auth configure-docker
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/content-optimizer-frontend

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy content-optimizer-frontend \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/content-optimizer-frontend \
            --region ${{ secrets.GCP_REGION }} \
            --platform managed \
            --allow-unauthenticated
